// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import EditableController from "./editable_controller.js"
application.register("editable", EditableController)

import FormatController from "./format_controller.js"
application.register("format", FormatController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
