// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AddFragmentController from "./add_fragment_controller.js"
application.register("add-fragment", AddFragmentController)

import ChangeFragmentController from "./change_fragment_controller.js"
application.register("change-fragment", ChangeFragmentController)

import ClipboardController from "./clipboard_controller.js"
application.register("clipboard", ClipboardController)

import EditableController from "./editable_controller.js"
application.register("editable", EditableController)

import FormatController from "./format_controller.js"
application.register("format", FormatController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PreController from "./pre_controller.js"
application.register("pre", PreController)
